/**
 * Seed & Dummy Data for JOBTRACKR
 * Realistic demo data matching PRD specifications
 */

export const INITIAL_USER = {
  id: 'usr_andrian_01',
  name: 'Andrian Syahputra',
  email: 'andrian@jobtrackr.io',
  role_title: 'Junior Software Engineer & Fullstack Dev',
  location: 'Jakarta, Indonesia',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
  target_role: 'Backend / Fullstack Engineer',
  target_salary: '15.000.000 - 25.000.000 IDR',
  created_at: '2026-08-01'
};

export const INITIAL_APPLICATIONS = [
  {
    id: 'app_01',
    user_id: 'usr_andrian_01',
    company_name: 'Tokopedia',
    position: 'Backend Developer',
    location: 'Jakarta',
    application_date: '2026-09-20',
    applied_via: 'LinkedIn',
    job_url: 'https://tokopedia.com/careers/backend-dev-2026',
    employment_type: 'Full Time',
    work_arrangement: 'Hybrid',
    salary_min: 18000000,
    salary_max: 24000000,
    currency: 'IDR',
    current_status: 'Interview',
    result: 'Interview',
    notes: 'HR menghubungi via LinkedIn. Technical interview dijadwalkan tanggal 25 September 2026 jam 14:00.',
    last_followed_up_at: null,
    created_at: '2026-09-20T10:00:00Z',
    updated_at: '2026-09-21T14:30:00Z'
  },
  {
    id: 'app_02',
    user_id: 'usr_andrian_01',
    company_name: 'PT Telkom Indonesia',
    position: 'IT Support',
    location: 'Jakarta',
    application_date: '2026-09-14',
    applied_via: 'JobStreet',
    job_url: 'https://careers.telkom.co.id/jobs/it-support',
    employment_type: 'Full Time',
    work_arrangement: 'On-site',
    salary_min: 10000000,
    salary_max: 14000000,
    currency: 'IDR',
    current_status: 'No Response',
    result: 'No Response',
    notes: 'CV dan portofolio sudah dikirim lewat JobStreet. Belum ada respons setelah 8 hari.',
    last_followed_up_at: null,
    created_at: '2026-09-14T09:00:00Z',
    updated_at: '2026-09-14T09:00:00Z'
  },
  {
    id: 'app_03',
    user_id: 'usr_andrian_01',
    company_name: 'GoTo Financial',
    position: 'Frontend Engineer',
    location: 'Jakarta',
    application_date: '2026-09-02',
    applied_via: 'Glints',
    job_url: 'https://gotocompany.com/careers/fe-eng',
    employment_type: 'Full Time',
    work_arrangement: 'Remote',
    salary_min: 25000000,
    salary_max: 32000000,
    currency: 'IDR',
    current_status: 'Approved',
    result: 'Approved',
    notes: 'Offering letter received! 🎉 Gaji pokok dan bonus performa disepakati. Masuk mulai 1 Oktober 2026.',
    last_followed_up_at: '2026-09-10',
    created_at: '2026-09-02T11:15:00Z',
    updated_at: '2026-09-18T16:00:00Z'
  },
  {
    id: 'app_04',
    user_id: 'usr_andrian_01',
    company_name: 'Shopee Indonesia',
    position: 'Software Engineer',
    location: 'Jakarta',
    application_date: '2026-09-18',
    applied_via: 'Company Website',
    job_url: 'https://careers.shopee.co.id/job/software-eng',
    employment_type: 'Full Time',
    work_arrangement: 'Hybrid',
    salary_min: 16000000,
    salary_max: 22000000,
    currency: 'IDR',
    current_status: 'Applied',
    result: 'Applied',
    notes: 'Submitted online assessment (HackerRank test selesai tanggal 19 September). Menunggu hasil evaluasi.',
    last_followed_up_at: null,
    created_at: '2026-09-18T08:30:00Z',
    updated_at: '2026-09-18T08:30:00Z'
  },
  {
    id: 'app_05',
    user_id: 'usr_andrian_01',
    company_name: 'Traveloka',
    position: 'Product Analyst',
    location: 'Jakarta',
    application_date: '2026-09-10',
    applied_via: 'LinkedIn',
    job_url: 'https://traveloka.com/careers/pa-2026',
    employment_type: 'Full Time',
    work_arrangement: 'Hybrid',
    salary_min: 15000000,
    salary_max: 20000000,
    currency: 'IDR',
    current_status: 'Interview',
    result: 'Interview',
    notes: 'Interview tahap 2 dengan Head of Product Analytics pada tanggal 24 September 2026 jam 10:00 WIB.',
    last_followed_up_at: null,
    created_at: '2026-09-10T14:20:00Z',
    updated_at: '2026-09-19T11:00:00Z'
  },
  {
    id: 'app_06',
    user_id: 'usr_andrian_01',
    company_name: 'Blibli',
    position: 'Fullstack Engineer',
    location: 'Jakarta',
    application_date: '2026-09-11',
    applied_via: 'Kalibrr',
    job_url: 'https://careers.blibli.com/fs-dev',
    employment_type: 'Full Time',
    work_arrangement: 'Hybrid',
    salary_min: 14000000,
    salary_max: 18000000,
    currency: 'IDR',
    current_status: 'No Response',
    result: 'No Response',
    notes: 'Sudah 11 hari belum ada kabar setelah tes koding awal. Perlu follow up ke HR.',
    last_followed_up_at: null,
    created_at: '2026-09-11T09:45:00Z',
    updated_at: '2026-09-11T09:45:00Z'
  },
  {
    id: 'app_07',
    user_id: 'usr_andrian_01',
    company_name: 'Startup ABC',
    position: 'Software Engineer',
    location: 'Bandung',
    application_date: '2026-09-15',
    applied_via: 'Company Website',
    job_url: 'https://startupabc.id/join',
    employment_type: 'Full Time',
    work_arrangement: 'On-site',
    salary_min: 9000000,
    salary_max: 13000000,
    currency: 'IDR',
    current_status: 'Applied',
    result: 'Applied',
    notes: 'CV dan portofolio GitHub sudah dikirim via Google Form karir.',
    last_followed_up_at: null,
    created_at: '2026-09-15T13:00:00Z',
    updated_at: '2026-09-15T13:00:00Z'
  },
  {
    id: 'app_08',
    user_id: 'usr_andrian_01',
    company_name: 'Company XYZ',
    position: 'Junior Developer',
    location: 'Remote',
    application_date: '2026-09-01',
    applied_via: 'Glints',
    job_url: '',
    employment_type: 'Contract',
    work_arrangement: 'Remote',
    salary_min: 8000000,
    salary_max: 11000000,
    currency: 'IDR',
    current_status: 'Rejected',
    result: 'Rejected',
    notes: 'Posisi dibekukan (hiring freeze) karena penyesuaian anggaran kuartal 4.',
    last_followed_up_at: null,
    created_at: '2026-09-01T10:00:00Z',
    updated_at: '2026-09-15T09:30:00Z'
  },
  {
    id: 'app_09',
    user_id: 'usr_andrian_01',
    company_name: 'Google Indonesia',
    position: 'Cloud Solutions Architect',
    location: 'Jakarta',
    application_date: '2026-09-22',
    applied_via: 'Referral',
    job_url: 'https://careers.google.com/jobs/results/cloud-sa',
    employment_type: 'Full Time',
    work_arrangement: 'Hybrid',
    salary_min: 35000000,
    salary_max: 48000000,
    currency: 'IDR',
    current_status: 'Applied',
    result: 'Applied',
    notes: 'Direferensikan oleh senior alumni kampus. Aplikasi baru disubmit pagi ini.',
    last_followed_up_at: null,
    created_at: '2026-09-22T08:00:00Z',
    updated_at: '2026-09-22T08:00:00Z'
  },
  {
    id: 'app_10',
    user_id: 'usr_andrian_01',
    company_name: 'DANA Indonesia',
    position: 'Mobile Engineer (React Native)',
    location: 'Jakarta',
    application_date: '2026-09-08',
    applied_via: 'LinkedIn',
    job_url: 'https://dana.id/career/mobile-eng',
    employment_type: 'Full Time',
    work_arrangement: 'Hybrid',
    salary_min: 19000000,
    salary_max: 26000000,
    currency: 'IDR',
    current_status: 'Interview',
    result: 'Interview',
    notes: 'Take home test dinilai baik. Sesi System Design Interview dijadwalkan 26 September 2026 jam 15:30 WIB.',
    last_followed_up_at: null,
    created_at: '2026-09-08T11:00:00Z',
    updated_at: '2026-09-17T17:00:00Z'
  },
  {
    id: 'app_11',
    user_id: 'usr_andrian_01',
    company_name: 'Tiket.com',
    position: 'QA Automation Engineer',
    location: 'Jakarta',
    application_date: '2026-08-28',
    applied_via: 'Indeed',
    job_url: 'https://tiket.com/careers/qa-auto',
    employment_type: 'Full Time',
    work_arrangement: 'Hybrid',
    salary_min: 12000000,
    salary_max: 16000000,
    currency: 'IDR',
    current_status: 'Rejected',
    result: 'Rejected',
    notes: 'Kandidat lain dipilih dengan pengalaman Cypress & Appium yang lebih senior.',
    last_followed_up_at: null,
    created_at: '2026-08-28T10:00:00Z',
    updated_at: '2026-09-05T14:00:00Z'
  },
  {
    id: 'app_12',
    user_id: 'usr_andrian_01',
    company_name: 'Bank Mandiri (Digital)',
    position: 'Java Backend Specialist',
    location: 'Jakarta',
    application_date: '2026-09-21',
    applied_via: 'JobStreet',
    job_url: 'https://bankmandiri.co.id/career',
    employment_type: 'Full Time',
    work_arrangement: 'On-site',
    salary_min: 13000000,
    salary_max: 17000000,
    currency: 'IDR',
    current_status: 'Applied',
    result: 'Applied',
    notes: 'Program Batch Intake Digital Talent 2026. Menunggu pengumuman berkas administrasi.',
    last_followed_up_at: null,
    created_at: '2026-09-21T15:20:00Z',
    updated_at: '2026-09-21T15:20:00Z'
  }
];

export const INITIAL_STATUS_HISTORY = [
  {
    id: 'hist_01',
    application_id: 'app_01',
    old_status: 'Applied',
    new_status: 'Interview',
    changed_at: '2026-09-21T14:30:00Z',
    note: 'Undangan technical interview via Google Meet diterima dari HR Tokopedia.'
  },
  {
    id: 'hist_02',
    application_id: 'app_03',
    old_status: 'Applied',
    new_status: 'Interview',
    changed_at: '2026-09-07T10:00:00Z',
    note: 'Lolos screening CV dan masuk tahap user interview.'
  },
  {
    id: 'hist_03',
    application_id: 'app_03',
    old_status: 'Interview',
    new_status: 'Approved',
    changed_at: '2026-09-18T16:00:00Z',
    note: 'Offering letter dikirimkan dan disepakati. Diterima! 🎉'
  },
  {
    id: 'hist_04',
    application_id: 'app_05',
    old_status: 'Applied',
    new_status: 'Interview',
    changed_at: '2026-09-19T11:00:00Z',
    note: 'HR Traveloka mengirim link Google Meet untuk interview tahap 2.'
  },
  {
    id: 'hist_05',
    application_id: 'app_08',
    old_status: 'Applied',
    new_status: 'Rejected',
    changed_at: '2026-09-15T09:30:00Z',
    note: 'Email penolakan resmi karena pembekuan rekrutmen tim internal.'
  },
  {
    id: 'hist_06',
    application_id: 'app_10',
    old_status: 'Applied',
    new_status: 'Interview',
    changed_at: '2026-09-17T17:00:00Z',
    note: 'Technical take home test lolos, lanjut ke System Design Interview.'
  },
  {
    id: 'hist_07',
    application_id: 'app_11',
    old_status: 'Applied',
    new_status: 'Rejected',
    changed_at: '2026-09-05T14:00:00Z',
    note: 'Email notifikasi penolakan dari HR Tiket.com.'
  }
];

export const INITIAL_APPLICATION_EVENTS = [
  {
    id: 'evt_01',
    application_id: 'app_01',
    event_type: 'Applied',
    event_date: '2026-09-20',
    title: 'Application Created',
    description: 'Submitted application for Backend Developer role via LinkedIn.'
  },
  {
    id: 'evt_02',
    application_id: 'app_01',
    event_type: 'Viewed',
    event_date: '2026-09-21',
    title: 'Application Viewed by HR',
    description: 'Recruiter at Tokopedia viewed CV and LinkedIn profile.'
  },
  {
    id: 'evt_03',
    application_id: 'app_01',
    event_type: 'Interview',
    event_date: '2026-09-25',
    title: 'Technical Coding Interview',
    description: '1-hour live coding session on Go/Distributed Systems with Senior Tech Lead.'
  },
  {
    id: 'evt_04',
    application_id: 'app_05',
    event_type: 'Interview',
    event_date: '2026-09-24',
    title: 'Product Case Study Interview',
    description: 'Case interview with Traveloka Product Team on flight booking funnel metrics.'
  },
  {
    id: 'evt_05',
    application_id: 'app_10',
    event_type: 'Interview',
    event_date: '2026-09-26',
    title: 'System Design Interview (DANA)',
    description: 'Architecture & high availability interview for e-wallet transaction flows.'
  },
  {
    id: 'evt_06',
    application_id: 'app_03',
    event_type: 'Approved',
    event_date: '2026-09-18',
    title: 'Official Job Offer Received 🎉',
    description: 'Received formal offer package with benefits and health insurance.'
  }
];

export const INITIAL_REMINDERS = [
  {
    id: 'rem_01',
    user_id: 'usr_andrian_01',
    application_id: 'app_01',
    title: 'Tokopedia Technical Interview Prep',
    reminder_date: '2026-09-25',
    reminder_time: '13:00',
    completed: false,
    created_at: '2026-09-21T15:00:00Z'
  },
  {
    id: 'rem_02',
    user_id: 'usr_andrian_01',
    application_id: 'app_02',
    title: 'Follow-up Email to PT Telkom HR',
    reminder_date: '2026-09-23',
    reminder_time: '09:30',
    completed: false,
    created_at: '2026-09-22T08:00:00Z'
  },
  {
    id: 'rem_03',
    user_id: 'usr_andrian_01',
    application_id: 'app_05',
    title: 'Traveloka Product Analytics Review',
    reminder_date: '2026-09-24',
    reminder_time: '08:30',
    completed: false,
    created_at: '2026-09-20T10:00:00Z'
  },
  {
    id: 'rem_04',
    user_id: 'usr_andrian_01',
    application_id: 'app_06',
    title: 'Check Blibli Portal for test status',
    reminder_date: '2026-09-23',
    reminder_time: '14:00',
    completed: false,
    created_at: '2026-09-22T09:00:00Z'
  }
];
